//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gissatalet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Français {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Français() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gissatalet.Français", typeof(Français).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dégager!.
        /// </summary>
        public static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez bien deviné !.
        /// </summary>
        public static string correct {
            get {
                return ResourceManager.GetString("correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points | Nom | Tentative.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez entrer un nombre !.
        /// </summary>
        public static string guessError {
            get {
                return ResourceManager.GetString("guessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez deviné supérieur au nombre..
        /// </summary>
        public static string guessHigh {
            get {
                return ResourceManager.GetString("guessHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez deviné inférieur au nombre..
        /// </summary>
        public static string guessLow {
            get {
                return ResourceManager.GetString("guessLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devinez un nombre entre 1 et 10.
        /// </summary>
        public static string guessText {
            get {
                return ResourceManager.GetString("guessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le meilleur score n&apos;existe pas, création du fichier....
        /// </summary>
        public static string higschoreCreate {
            get {
                return ResourceManager.GetString("higschoreCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenant, une partie est lancée, entrez votre nom:.
        /// </summary>
        public static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger la police ASCII.
        /// </summary>
        public static string loadingFont {
            get {
                return ResourceManager.GetString("loadingFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune connexion Internet trouvée. Utilise la police précédente ou par défaut..
        /// </summary>
        public static string loadingFontError {
            get {
                return ResourceManager.GetString("loadingFontError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement des meilleurs scores.....
        /// </summary>
        public static string loadingHighscore {
            get {
                return ResourceManager.GetString("loadingHighscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fais un choix:.
        /// </summary>
        public static string MakeAMove {
            get {
                return ResourceManager.GetString("MakeAMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Jouez à Devinez le nombre !.
        /// </summary>
        public static string optionOne {
            get {
                return ResourceManager.GetString("optionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Quittez :(.
        /// </summary>
        public static string optionThree {
            get {
                return ResourceManager.GetString("optionThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Voir les meilleurs scores !.
        /// </summary>
        public static string optionTwo {
            get {
                return ResourceManager.GetString("optionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez sur (N) pour quitter ou appuyez sur n&apos;importe quelle touche pour continuer..
        /// </summary>
        public static string press {
            get {
                return ResourceManager.GetString("press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez sur n&apos;importe quelle touche pour revenir au menu principal.
        /// </summary>
        public static string pressAny {
            get {
                return ResourceManager.GetString("pressAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score élevé!.
        /// </summary>
        public static string TitelHighscore {
            get {
                return ResourceManager.GetString("TitelHighscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le nombre.
        /// </summary>
        public static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOUVEAU JEU!.
        /// </summary>
        public static string TitleNewGame {
            get {
                return ResourceManager.GetString("TitleNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le top 3 des meilleurs jeux.
        /// </summary>
        public static string top3 {
            get {
                return ResourceManager.GetString("top3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ont.
        /// </summary>
        public static string userBackHas {
            get {
                return ResourceManager.GetString("userBackHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points sur.
        /// </summary>
        public static string userBackScore {
            get {
                return ResourceManager.GetString("userBackScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tentative.
        /// </summary>
        public static string userBackTries {
            get {
                return ResourceManager.GetString("userBackTries", resourceCulture);
            }
        }
    }
}
