//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gissatalet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RövarSpråket {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RövarSpråket() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gissatalet.RövarSpråket", typeof(RövarSpråket).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KoKlolaror!.
        /// </summary>
        public static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoDu gogisossosadode rorätottot!.
        /// </summary>
        public static string correct {
            get {
                return ResourceManager.GetString("correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoPoänongog | NoNamomnon | FoFörorsosökok.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoDu momåsostote soskokrorivova inon etottot nonumommomeror!.
        /// </summary>
        public static string guessError {
            get {
                return ResourceManager.GetString("guessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoDu gogisossosadode hohögogrore änon totaloletot..
        /// </summary>
        public static string guessHigh {
            get {
                return ResourceManager.GetString("guessHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoDu gogisossosadode lolägogrore änon totaloletot..
        /// </summary>
        public static string guessLow {
            get {
                return ResourceManager.GetString("guessLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoGisossosa etottot nonumommomeror momelollolanon 1 - 10.
        /// </summary>
        public static string guessText {
            get {
                return ResourceManager.GetString("guessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoHigoghohsoscocorore fofinonnonsos inontote, soskokapoparor fofilol....
        /// </summary>
        public static string higschoreCreate {
            get {
                return ResourceManager.GetString("higschoreCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoNu sostotarortotasos etottot sospopelol soskokrorivov doditottot nonamomnon:.
        /// </summary>
        public static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoLadoddodaror noneror ASoSCoCII FoFonontot.
        /// </summary>
        public static string loadingFont {
            get {
                return ResourceManager.GetString("loadingFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inongogenon inontoterornonetotanonsoslolutotnoninongog hohitottotadodesos. Anonvovänondoderor totidodigogarore totypopsosnonitottot elolloleror dodefofauloltot..
        /// </summary>
        public static string loadingFontError {
            get {
                return ResourceManager.GetString("loadingFontError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoLadoddodaror HoHigoghohsoscocorore.....
        /// </summary>
        public static string loadingHighscore {
            get {
                return ResourceManager.GetString("loadingHighscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoGöror etottot vovalol:.
        /// </summary>
        public static string MakeAMove {
            get {
                return ResourceManager.GetString("MakeAMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) SoSpopelola GoGisossosa ToTaloletot!.
        /// </summary>
        public static string optionOne {
            get {
                return ResourceManager.GetString("optionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Avovsoslolutota :(.
        /// </summary>
        public static string optionThree {
            get {
                return ResourceManager.GetString("optionThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) SoSe HoHigoghohsoscocorore!.
        /// </summary>
        public static string optionTwo {
            get {
                return ResourceManager.GetString("optionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToTrorycockok popå (NoN) foföror atottot avovsoslolutota elolloleror, ToTrorycockok popå vovalolfofrori totanongogenontot foföror atottot foforortotsosätottota..
        /// </summary>
        public static string press {
            get {
                return ResourceManager.GetString("press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToTrorycockok popå vovalolfofrori koknonapoppop foföror atottot åtoterorgogå totilollol hohuvovudodmomenonynon.
        /// </summary>
        public static string pressAny {
            get {
                return ResourceManager.GetString("pressAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoHigohScore!.
        /// </summary>
        public static string TitelHighscore {
            get {
                return ResourceManager.GetString("TitelHighscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToTaloletot.
        /// </summary>
        public static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoGAMoME!.
        /// </summary>
        public static string TitleNewGame {
            get {
                return ResourceManager.GetString("TitleNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoDe totopop 3 BoBäsostota sospopelolanona.
        /// </summary>
        public static string top3 {
            get {
                return ResourceManager.GetString("top3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hoharor.
        /// </summary>
        public static string userBackHas {
            get {
                return ResourceManager.GetString("userBackHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popoänongog popå.
        /// </summary>
        public static string userBackScore {
            get {
                return ResourceManager.GetString("userBackScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foförorsosökok.
        /// </summary>
        public static string userBackTries {
            get {
                return ResourceManager.GetString("userBackTries", resourceCulture);
            }
        }
    }
}
